### PR TITLE
uploading index.html -main page

### PR DESCRIPTION
**Pull request by xmkchen**
added responsive toggle top navbar and footer

### CODE REVIEW

**Comment by amandat85** [comment]
I'm stashing my files and going through yours to resolve some merge issues.

**Comment by amandat85** [comment]
I can go ahead and merge changes but there is an issue with the image sizing and the recipe /restaurant area if I do

**Comment by xmkchen** [comment]
Thanks for noticing it. I'm currently working of rectifying the image and
recipes and restaurant grid. Will have another pull request when it's good
to go.

**Comment by amandat85** [comment]
It might take me all night to figure out how to merge it. lol.

**Pull request closed without merging**
